import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);
		
		double totalKids = 0.0; //the total kids for average
		int twoChild = 0; //family's number with 2 children
		int threeChild = 0; //family's number with 3 children
		int fourChild = 0;//family's number with 4 children or more
		
		//make random family T times
		
		for (int i = 1 ; i <= T ; i++ ){
		int girl = 0; // number of girls
		int boy = 0; //number of boys
		int kids = 0; //sum of the kids
			while ( boy == 0 || girl == 0){
				double rnd = generator.nextDouble();
				if ( rnd > 0.5 ){girl++ ;}
				else {boy++ ;}
				kids = girl + boy ;
				}
				totalKids += kids ; 
			if( kids == 2 ){twoChild++ ;}
			else if( kids == 3 ){threeChild++ ;}
			else {fourChild++ ;}
		}
		
		//print the result and the average
		double average = totalKids/(double)T ;
		System.out.println( "Average: " + average + " children to get at least one of each gender." );
		System.out.println( "Number of families with 2 children: " + twoChild );
		System.out.println( "Number of families with 3 children: " + threeChild );
		System.out.println( "Number of families with 4 or more children: " + fourChild );
		
		//check which is the common family kids number
		if ( twoChild > threeChild && twoChild > fourChild ){System.out.println( "The most common number of children is 2." );}
		else if ( threeChild > twoChild && threeChild > fourChild ){System.out.println( "The most common number of children is." );}
		else {System.out.println( "The most common number of children is 4 or more." );}
  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
